### ISSUE TITLE
Improve URL Semantics

### ISSUE THREAD

**Issue by TobiasRoeddiger** [teco-kit/explorer#6]
projects are uniquly identified by the person that created it (admin/owner) and the name of the project. Therefore an admin can only have on repository with the same name.

This will serve to have a improved url. A project is identified by: /:username/:projectname

Other routes then may be:
- /:username/:projectname/datasets 
- ....

**Comment by tk-king** [comment]
Change url from projectId to projectName and enforce URL friendly characters in the projectName.
